### ISSUE TITLE
Unicode-Support

### ISSUE THREAD

**Issue by aknrdureegaesr** [innoq/iBlog#57]
Beobachtung: Ein &#x2192; einfach mit Cut+Paste hat nicht funktioniert.

Workaround: Quoten als &amp;#x2192; ging.

Noch zu untersuchen: Liegt das am Browser oder an iBlog?

**Comment by mjansing** [comment]
Should be fixed in #196.

**Comment by aknrdureegaesr** [comment]
Sorry, still does not work. I copied the Unicode character 😊 into the title of a blog and some random Greek letters plus a ♡ into its text. Preview worked fine, but I got an error when trying to save it: 

> We're sorry, but something went wrong.

**Comment by tloist** [comment]
Kann ich leider bestätigen

**Comment by mjansing** [comment]
It looks like we have to switch to mysql's [utf8mb4][utf8mb4] to be full unicode compliant. Something like `私のホバークラフトは鰻でいっぱいです ♡⚠` works fine.

[utf8mb4]: https://mathiasbynens.be/notes/mysql-utf8mb4

**Comment by mjansing** [comment]
Fixed with dcf4e932c898783681bac9bbd2034fa385e48c3c. I switched database encoding to utf8mb4 which is mysql encoding for __real__ unicode support.
